# Cdkey 兑换码插件
# 作者：Month_Light

# 插件版本号
version: 1.2

# 数据库配置
MySQL:
  
  # 数据库的名称
  mySQLDatabase: moonlake_cdkey

  # 数据库的地址
  mySQLHost: 127.0.0.1

  # 数据库的端口
  mySQLPort: 3306

  # 数据库的用户名
  mySQLUsername: root

  # 数据库的密码
  mySQLPassword: moonlake

  # 数据库的表名
  mySQLTableName: cdkey_{0}
  
  # 数据库的过期表名
  mySQLTableCacheName: cache